fos_rest:
    versioning:
      enabled: true
      resolvers:
        query: false
        custom_header: false
        media_type:
          enabled: false
    routing_loader:
      default_format: json
      include_format: false
    param_fetcher_listener: true
    allowed_methods_listener: false
    view:
      view_response_listener: false
    format_listener:
      rules:
        - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
