lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_SECRET_KEY)%'
    public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        '3600'
    user_identity_field: email

    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: false
        query_parameter:
            enabled: false
